{% set name = "aplpy" %}
{% set version = "2.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "618ff478ec5bc4cbc05dc04f2ea9f7f1781b8d7ac467fd4b115c99d72db4cc7a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/APLpy-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - astropy
  run:
    - python
    - astropy
    - matplotlib

test:
  imports:
    - aplpy

about:
  home: http://aplpy.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: The Astronomical Plotting Library in Python
  description: |
    APLpy (the Astronomical Plotting Library in Python) is a Python module
    aimed at producing publication-quality plots of astronomical imaging data
    in FITS format.
  doc_url: http://aplpy.readthedocs.io
  dev_url: https://github.com/aplpy/aplpy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - astrofrog-conda-forge
