travis:
  secure:
    BINSTAR_TOKEN: UdueYjAJ0WKM6dmjspFbLmFWY1gkM2ZY/5+6pV4D1ZOzQ2C1Me5yu8gWbXFAy3bHSn11DDz5ZujiXtMQNdK3wWxkMRiiIL+Nncv5c/FjPPfGVwbtR3S/fvLTKWHWEZq5IvxVV7MO0wTsdGU6O58WTi3FaGRIdyMfBvt5G+3Ji2q3GrPfGYe4XVv0icZ8f+MLoYhZnHMzABLoxQntp5RmDhf2G+jld8nkmlVbS3HCKRNy/7TUH7wklZ/1tAYw/1mdBX+0NiIJMIZBwxgVM5hL7v+Bc2Zom56istcAUKJ7zDc4jhd1jTUdJMEr4z0Exfx+L6ThEfpcK9YnySmGAybg0n5gT/6EhSbuK0xJ2zBeViLOuBh9YN2vhFArRkgCQOH+x4mppv5rec+O5/H4/r7EXlyXae41s0Gngu5HKWI29NMErnCaA//M8m54baPJiSAqWBX63kdPhrRgsVHylH0DMXpmUUpKOHA6sqlYhM/hCeRlQDuzOVsBO3jTJLu7u/4bCBiD17g+A1kbxdlIX6KGrszA0E2KKHsSczuqe6OwYkr/ZAyCp84oX+ARiWanuh6dBGRaw/A4jHJzvYF4p86JIWOBCxYsmVYD+tpL5a+J/+2FQzB9+QkyB9BiKVIM8F4LdFDikWlkGsen6HpH+Q0d7Nwzg/ywm8EWc9dyxF+nOVI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
