travis:
  secure:
    BINSTAR_TOKEN: xsrVujk6bIDv2uj6lS6RA/jPp82AvqCyqs3NvN8mwcQrgaRZYe7OvKAUoxzUB/Y7EQd9MVYymlxa2zVvpqPSiTP0g1+yBM93IBQECiVdtCks5xXz/JwYQA9c+y/QMMHXRRR++N/N5cPGJYBoe3dJH8gdt+vL5uAYczB6qo8521Fn+hScweAgV1/BEsZe4wmMGbNS2TeVE98316xl534OiDwbBMaEe0YIxAp+MmwV7XBpPyMxlf4m5a42uPX31mn8m9eOlI5rkawWkwSmjrKaYByj6ZvsVcLoJRz74E1cYZaOY7Bxa21sNAZkSWbZr06fVarNneeQN9MsYhYd05b+ozVAf5Y9Fk0zNpkB+uTZimTNpqW6p8vS6eYrxzx03NFaggHkb/R8uHVBm+PC3B4pVHm7FLmcxKkUPXRWhdWV6AufUPXbWUuucwS2EgZj1y6Boa7MRVNlg57eV2KIWhMPEXl2BPGoOn+1OvXJPuLua5xb/PZGK7MKUu1H6P8TMWxyMPf2iCHSxlOi+P9XDb/6JF0YwhJ8DX2+joM6q1jRDmMLOnm1fvaX4nFAN2zwaSo3Dy6ddgppWSDlFeA0dFOZ3iIY31RzmVhjBsrbTr0RQBKATyUQrLDdLJk4yBBodMUV9uFbWJRPXB/SldqXPWn6WFonVxSfDCmwyM26ebNu+s8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
